; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28106.4 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Emre\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
